export const jobsData = [
  {
    id: "1",
    company: "XYZ Technology",
    title: "UI/UX Designer",
    location: "Washington, DC",
    phone: "+880-1455555555",
    experience: "1-2 Y",
    rating: 4.9,
    reviews: 56,
    skills: ["Figma", "Adobe Illustrator", "Adobe Photoshop", "Adobe XD"],
    salary: 4500,
    uploadedDaysAgo: 2,
    employmentType: "Full-Time",
    workArrangement: "On-Site",
    careerLevel: "Mid-Level",
    industry: "Technology & IT",
    flexibility: "Flexible Hours",
    specialOpportunities: "Internship",
    salaryRange: "40000-60000",
  },
  {
    id: "2",
    company: "Tech Solutions",
    title: "Frontend Developer",
    location: "Remote",
    phone: "+880-1455555556",
    experience: "2-3 Y",
    rating: 4.8,
    reviews: 42,
    skills: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
    salary: 5500,
    uploadedDaysAgo: 1,
    employmentType: "Full-Time",
    workArrangement: "Remote",
    careerLevel: "Mid-Level",
    industry: "Technology & IT",
    flexibility: "Flexible Hours",
    specialOpportunities: "Apprenticeship",
    salaryRange: "40000-60000",
  },
  {
    id: "3",
    company: "Digital Agency",
    title: "Graphic Designer",
    location: "Maryland",
    phone: "+880-1455555557",
    experience: "1-2 Y",
    rating: 4.7,
    reviews: 38,
    skills: ["Adobe Creative Suite", "Figma", "Branding", "UI Design"],
    salary: 3800,
    uploadedDaysAgo: 3,
    employmentType: "Part-Time",
    workArrangement: "Hybrid",
    careerLevel: "Entry-Level",
    industry: "Marketing & Communications",
    flexibility: "Shift Work",
    specialOpportunities: "Volunteer",
    salaryRange: "20000-40000",
  },
  {
    id: "4",
    company: "Finance Corp",
    title: "Financial Analyst",
    location: "Washington, DC",
    phone: "+880-1455555558",
    experience: "3-5 Y",
    rating: 4.6,
    reviews: 51,
    skills: ["Excel", "SQL", "Python", "Financial Modeling"],
    salary: 6500,
    uploadedDaysAgo: 2,
    employmentType: "Full-Time",
    workArrangement: "On-Site",
    careerLevel: "Senior-Level",
    industry: "Finance & Accounting",
    flexibility: "Flexible Hours",
    specialOpportunities: "Diversity & Inclusion",
    salaryRange: "60000-80000",
  },
  {
    id: "5",
    company: "Healthcare Plus",
    title: "Nurse Practitioner",
    location: "Virginia",
    phone: "+880-1455555559",
    experience: "2-4 Y",
    rating: 4.9,
    reviews: 67,
    skills: [
      "Patient Care",
      "Medical Assessment",
      "Diagnosis",
      "Treatment Planning",
    ],
    salary: 7200,
    uploadedDaysAgo: 1,
    employmentType: "Full-Time",
    workArrangement: "On-Site",
    careerLevel: "Senior-Level",
    industry: "Healthcare",
    flexibility: "Night Shift",
    specialOpportunities: "Apprenticeship",
    salaryRange: "60000-80000",
  },
  {
    id: "6",
    company: "Education Hub",
    title: "Math Teacher",
    location: "Remote",
    phone: "+880-1455555560",
    experience: "1-3 Y",
    rating: 4.5,
    reviews: 29,
    skills: [
      "Mathematics",
      "Teaching",
      "Curriculum Design",
      "Student Assessment",
    ],
    salary: 3200,
    uploadedDaysAgo: 4,
    employmentType: "Contract",
    workArrangement: "Remote",
    careerLevel: "Entry-Level",
    industry: "Education",
    flexibility: "Flexible Hours",
    specialOpportunities: "Internship",
    salaryRange: "20000-40000",
  },
  {
    id: "7",
    company: "Cloud Systems",
    title: "DevOps Engineer",
    location: "Remote",
    phone: "+880-1455555561",
    experience: "3-5 Y",
    rating: 4.8,
    reviews: 44,
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    salary: 8000,
    uploadedDaysAgo: 2,
    employmentType: "Full-Time",
    workArrangement: "Remote",
    careerLevel: "Senior-Level",
    industry: "Technology & IT",
    flexibility: "Flexible Hours",
    specialOpportunities: "Diversity & Inclusion",
    salaryRange: "80000-999999",
  },
  {
    id: "8",
    company: "Marketing Pro",
    title: "Digital Marketing Manager",
    location: "Maryland",
    phone: "+880-1455555562",
    experience: "2-4 Y",
    rating: 4.6,
    reviews: 35,
    skills: ["SEO", "Social Media", "Content Marketing", "Analytics"],
    salary: 5000,
    uploadedDaysAgo: 3,
    employmentType: "Full-Time",
    workArrangement: "Hybrid",
    careerLevel: "Mid-Level",
    industry: "Marketing & Communications",
    flexibility: "Flexible Hours",
    specialOpportunities: "Apprenticeship",
    salaryRange: "40000-60000",
  },
  {
    id: "9",
    company: "Startup Ventures",
    title: "Product Manager",
    location: "Washington, DC",
    phone: "+880-1455555563",
    experience: "2-3 Y",
    rating: 4.7,
    reviews: 28,
    skills: ["Product Strategy", "User Research", "Analytics", "Agile"],
    salary: 6200,
    uploadedDaysAgo: 1,
    employmentType: "Full-Time",
    workArrangement: "Hybrid",
    careerLevel: "Mid-Level",
    industry: "Technology & IT",
    flexibility: "Flexible Hours",
    specialOpportunities: "Volunteer",
    salaryRange: "60000-80000",
  },
  {
    id: "10",
    company: "Retail Chain",
    title: "Store Manager",
    location: "Virginia",
    phone: "+880-1455555564",
    experience: "3-5 Y",
    rating: 4.4,
    reviews: 22,
    skills: ["Team Management", "Sales", "Customer Service", "Inventory"],
    salary: 4200,
    uploadedDaysAgo: 5,
    employmentType: "Full-Time",
    workArrangement: "On-Site",
    careerLevel: "Senior-Level",
    industry: "Retail & Sales",
    flexibility: "Weekend Only",
    specialOpportunities: "Diversity & Inclusion",
    salaryRange: "40000-60000",
  },
];

export const companiesData = [
  {
    id: "1",
    name: "XYZ Technology",
    type: "Software Company",
    employees: 250,
    rating: 4.9,
    image: "/tech-company.jpg",
  },
  {
    id: "2",
    name: "Tech Solutions",
    type: "Software Company",
    employees: 180,
    rating: 4.8,
    image: "/tech-solutions.jpg",
  },
  {
    id: "3",
    name: "Digital Agency",
    type: "Creative Agency",
    employees: 95,
    rating: 4.7,
    image: "/digital-agency.jpg",
  },
];
