// app/admin-dashboard/layout.tsx

import React from "react";
import { AppSidebar } from "@/components/ui/app-sidebar-admin";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ The layout must be named `Layout` (not "DasboardLayout") and exported as default
export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="sticky top-0 z-40 flex h-18 shrink-0 items-center border-b bg-primary/95 backdrop-blur transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-16 justify-between px-4 lg:px-6 xl:px-8">
          <div className="flex items-center gap-2">
            <SidebarTrigger className="md:hidden" />
            <div className="text-white">
              <h1 className="text-2xl">Welcome Back</h1>
              <p className="text-sm">Admin</p>
            </div>
          </div>
          <div>
            <Image
              src="/dashboard/profile.png"
              height={50}
              width={50}
              alt="Dashboard Profile Image"
              className="rounded-full"
            />
          </div>
        </header>

        <main className="overflow-hidden p-4 lg:p-6 xl:p-8 min-h-dvh">
          {children}
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
