import type { Metadata } from "next";

import "./globals.css";
import ReduxWrapper from "@/redux/ReduxWrapper";
import { ModalProvider } from "@/components/provider/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxWrapper>
          {children} <ModalProvider />
        </ReduxWrapper>
      </body>
    </html>
  );
}
