import Footer from "@/components/common/footer/footer";
import { Navbar } from "@/components/common/navbar/navabar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="!overflow-hidden min-h-screen">{children}</main>
    </>
  );
}
